- name: Create content volumes
  community.general.docker_volume:
    name: "{{item.name}}"
    recreate: options-changed
    driver_options:
      type: "nfs4"
      device: ":/volume1/content/{{ item.path }}"
      o: "addr=192.168.10.38"
  loop:
    - {name: books_vol, path: "books"}
    - {name: comics_vol, path: "Comics"}
    - {name: complete_downloads_vol, path: "Downloads/complete"}
    - {name: incomplete_downloads_vol, path: "Downloads/incomplete"}
    - {name: watch_downloads_vol, path: "Downloads/watch"}
    - {name: movies_vol, path: "Movies"}
    - {name: tv_vol, path: "TV"}
    - {name: misc_vids_vol, path: "Misc Videos"}
    # - {name: tubearchivist_vol, path: "tubearchivist"}
    - {name: tubesync_vol, path: "tubesync"}
- name: Create smb comics volume
  community.general.docker_volume:
    name: "comics_smb_vol"
    recreate: "options-changed"
    driver_options:
      type: "cifs"
      device: "//192.168.10.38/content/Comics"
      o: "addr=192.168.10.38,username=ipreston,password={{ laconia_pass}},file_mode=0777,dir_mode=0777"
