cert-manager:
  crds:
    enabled: true
    keep: true
  replicaCount: 3
  podDisruptionBudget:
    enabled: true

  # ingressShim:
  #   defaultIssuerName: letsencrypt-prod
  #   defaultIssuerKind: ClusterIssuer

#   prometheus:
#     enabled: true
#     servicemonitor:
#       enabled: true
#
# cloudflareApiToken: cloudflare-api-token
