apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
spec:
  chart:
    spec:
      chart: reloader
      sourceRef:
        kind: HelmRepository
        name: reloader
      # renovate: datasource=helm depName=reloader registryUrl=https://stakater.github.io/stakater-charts
      version: "2.2.3"
