---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bandicoot-stage
  labels:
    app: bandicoot
    env: stage
    ver: "2"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bandicoot
      env: stage
  template:
    metadata:
      labels:
        app: bandicoot
        env: stage
        ver: "2"
    spec:
      containers:
        - name: bandicoot-stage
          image: gcr.io/kuar-demo/kuard-amd64:blue
