---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bitwardenids
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    # This name must match the metadata.name in the `SecretStore`
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: projectid
    remoteRef:
      key: "projectid"
  - secretKey: organizationid
    remoteRef:
      key: "organizationid"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: githubkey
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    # This name must match the metadata.name in the `SecretStore`
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: argocd-github-installation-id
    remoteRef:
      key: "argocd-github-installation-id"
  - secretKey: argocd-github-app-id
    remoteRef:
      key: "argocd-github-app-id"
  - secretKey: argocd-github-app-key
    remoteRef:
      key: "argocd-github-app-key"

