---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-web-ui-cert
  namespace: argocd
spec:
  secretName: argo-web-ui-tls
  dnsNames:
    - argo.dk8s.ipreston.net
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argo-ingress
  namespace: argocd
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`argocd.dk8s.ipreston.net`)  # <-- Replace with your FQDN
      priority: 10
      kind: Rule
      services:
        - name: argocd-server
          port: 80
    - match: Host(`argocd.dk8s.ipreston.net`) && Header(`Content-Type`, `application/grpc`)
      priority: 11
      services:
          - name: argocd-server
            port: 80
            scheme: h2c
tls:
    secretName: argo-web-ui-tls

