---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-web-ui-cert
  namespace: argocd
spec:
  secretName: argo-web-ui-tls
  dnsNames:
    - argocd.<path:subdomain#SUBDOMAIN>
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argo-ingress
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`argocd.<path:subdomain#SUBDOMAIN>`)  # <-- Replace with your FQDN
      priority: 10
      kind: Rule
      services:
        - name: argocd-server
          port: 80
    - match: Host(`argocd.<path:subdomain#SUBDOMAIN>`) && Header(`Content-Type`, `application/grpc`)
      priority: 11
      services:
          - name: argocd-server
            port: 80
            scheme: h2c
  tls:
    secretName: argo-web-ui-tls

