---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-web-ui-cert
  namespace: argocd
spec:
  secretName: argo-web-ui-tls
  dnsNames:
    - argo.dk8s.ipreston.net
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argo-ingress
  namespace: argocd
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`argo.dk8s.ipreston.net`)  # <-- Replace with your FQDN
      kind: Rule
      services:
        - name: argocd-server
          port: 443
tls:
    secretName: argo-web-ui-tls

