---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: argo-repo
  namespace: argocd
stringData:
  type: git
  url: https://github.com/ianepreston/homelab
  githubAppID: "<path:githubkey#argocd-github-app-id>"
  githubAppInstallationID: "<path:githubkey#argocd-github-installation-id>"
  githubAppPrivateKey: |
    <path:githubkey#argocd-github-app-key>
type: Opaque
