# yaml-language-server: $schema=https://kube-schemas.pages.dev/cilium.io/ciliumloadbalancerippool_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: trust-pool
spec:
  blocks:
    - start: "192.168.15.21"
      stop: "192.168.15.26"
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/cilium.io/ciliumloadbalancerippool_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: guest-pool
spec:
  blocks:
    - start: "192.168.30.33"
      stop: "192.168.30.36"
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/cilium.io/ciliumloadbalancerippool_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: lab-pool
spec:
  blocks:
    - start: "192.168.40.21"
      stop: "192.168.40.30"
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/cilium.io/ciliumbgppeeringpolicy_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: bgp-peering-policy-pfsense
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: "linux" # just match everything
  virtualRouters:
    - localASN: 64513
      serviceSelector:
        matchExpressions:
          - {key: "io.cilium/bgp-announce", operator: NotIn, values: ['fakevalue']} # Should match all
      neighbors:
        - peerAddress: '192.168.40.1/32'
          peerASN: 64512
          eBGPMultihopTTL: 10
          connectRetryTimeSeconds: 120
          holdTimeSeconds: 90
          keepAliveTimeSeconds: 30
          gracefulRestart:
            enabled: true
            restartTimeSeconds: 120
