# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patchesJson6902:
  - target:
      group: cilium.io
      version: v2alpha1
      kind: CiliumBGPPeeringPolicy
      name: bgp-peering-policy-pfsense
    path: patch-bgp.json
  - target:
      group: cilium.io
      version: v2alpha1
      kind: CiliumLoadBalancerIPPool
      name: ip-pool
    path: patch-ippool.json
