---

- name: Create tubesync network
  community.docker.docker_network:
    name: tubesync_network

- name: Create tubesync config volume
  community.docker.docker_volume:
    name: tubesync_config_vol

- name: Create tubesync container
  community.docker.docker_container:
    name: tubesync
    hostname: tubesync
    state: started
    image: ghcr.io/meeb/tubesync:v0.13.7
    networks:
      - name: tubesync_network
      - name: traefik_net
    volumes:
      - tubesync_vol:/downloads
      - tubesync_config_vol:/config
    env:
      TZ: "America/Edmonton"
      PUID: "1026"
      PGID: "100"
    devices:
      - "/dev/dri:/dev/dri"
    labels:
      traefik.enable: "true"
      traefik.http.routers.tubesync.entrypoints: https
      traefik.http.routers.tubesync.rule: Host(`tubesync.{{ subdomain }}.ipreston.net`)
      traefik.http.routers.tubesync.tls: "true"
      traefik.http.routers.tubesync.middlewares: "chain-no-auth@file"
      traefik.http.routers.tubesync.service: tubesync
      traefik.http.services.tubesync.loadbalancer.server.port: "4848"
