# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
set: [pipefail]
shopt: [globstar]
vars:
  BOOSTRAP_DIR: '{{.ROOT_DIR}}/bootstrap'
  CLUSTER: '{{.CLUSTER | default "dev"}}'
  CLUSTER_APPS: '{{.ROOT_DIR}}/k8s/apps/{{.CLUSTER}}'
  CLUSTER_DIR: '{{.ROOT_DIR}}/k8s/clusters/{{.CLUSTER}}'
  SCRIPTS_DIR: '{{.ROOT_DIR}}/scripts'
  SHARED_APPS: '{{.ROOT_DIR}}/k8s/apps/base'
  TALOS_DIR: '{{.ROOT_DIR}}/talos/{{.CLUSTER}}'
  TALOS_CONFIG_DIR: '{{.ROOT_DIR}}/talos/{{.CLUSTER}}/clusterconfig'
  TERRAFORM_DIR: '{{.ROOT_DIR}}/terraform'
  ANSIBLE_DIR: '{{.ROOT_DIR}}/ansible'
dotenv:
  - '{{.ROOT_DIR}}/bws.env'
  # - '{{.SHARED_APPS}}/kube-tools/system-upgrade/versions.env'
env:
  # KUBECONFIG: '{{.CLUSTER_DIR}}/kubeconfig'
  # MINIJINJA_CONFIG_FILE: '{{.ROOT_DIR}}/.minijinja.toml'
  # SOPS_AGE_KEY_FILE: '{{.ROOT_DIR}}/age.key'
  TALOSCONFIG: '{{.TALOS_DIR}}/clusterconfig/talosconfig'
includes:
  ansible: taskfiles/ansible
  bootstrap: taskfiles/bootstrap
  status: taskfiles/status
  talos: taskfiles/talos
# kubernetes: .taskfiles/kubernetes
# op: .taskfiles/onepassword
# sops: .taskfiles/sops
# talos: .taskfiles/talos
# volsync: .taskfiles/volsync
# workstation: .taskfiles/workstation
tasks:
  default:
    cmd: task --list
    silent: true
  set_context:
    desc: "Set kubernetes and talos context"
    preconditions:
      - test -f {{.CLUSTER_DIR }}/kubeconfig
    cmds:
      - echo "# Generated by set_context task" > {{.ROOT_DIR}}/k8s.env
      - echo "KUBECONFIG={{.CLUSTER_DIR }}/kubeconfig" >> {{.ROOT_DIR}}/k8s.env
      - echo "TALOSCONFIG={{.TALOS_CONFIG_DIR}}/talosconfig" >> {{.ROOT_DIR}}/k8s.env
      - echo "context set to {{.CLUSTER}}"
  unset_context:
    desc: "Remove kubernetes and talos context"
    cmd: echo "# Generated by unset_context task" > {{.ROOT_DIR}}/k8s.env

# Ref: https://github.com/go-task/task/issues/608
# noop:
#   internal: true
#   silent: true
#   cmd: noop() { :; }
