# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
set: [pipefail]
shopt: [globstar]
vars:
  BOOTSTRAP_DIR: '{{.ROOT_DIR}}/bootstrap'
  CLUSTER: '{{.CLUSTER | default "dev"}}'
  CLUSTER_APPS: '{{.ROOT_DIR}}/k8s/apps'
  CLUSTER_DIR: '{{.ROOT_DIR}}/k8s/clusters/{{.CLUSTER}}'
  SCRIPTS_DIR: '{{.ROOT_DIR}}/scripts'
  KUBECONFIG: '{{.CLUSTER_DIR}}/kubeconfig'
  TALOS_DIR: '{{.ROOT_DIR}}/talos/{{.CLUSTER}}'
  TALOS_CONFIG_DIR: '{{.ROOT_DIR}}/talos/{{.CLUSTER}}/clusterconfig'
  TERRAFORM_DIR: '{{.ROOT_DIR}}/terraform'
  ANSIBLE_DIR: '{{.ROOT_DIR}}/ansible'
  PROJECT_NAME: 'k8s{{.CLUSTER}}'
  BWS_PROJECT:
    sh: |
      bws project list | jq -r --arg name '{{.PROJECT_NAME}}' '
        map(select(.name == $name)) | .[0].id // empty'
  BWS_ORG:
    sh: |
      bws project list | jq -r --arg name '{{.PROJECT_NAME}}' '
        map(select(.name == $name)) | .[0].organizationId // empty'
dotenv:
  - '{{.ROOT_DIR}}/bws.env'
  # - '{{.SHARED_APPS}}/kube-tools/system-upgrade/versions.env'
env:
  KUBECONFIG: '{{.CLUSTER_DIR}}/kubeconfig'
  MINIJINJA_CONFIG_FILE: '{{.ROOT_DIR}}/.minijinja.toml'
  TALOSCONFIG: '{{.TALOS_CONFIG_DIR}}/talosconfig'
includes:
  ansible: taskfiles/ansible
  bootstrap: taskfiles/bootstrap
  status: taskfiles/status
  talos: taskfiles/talos
# kubernetes: .taskfiles/kubernetes
# op: .taskfiles/onepassword
# sops: .taskfiles/sops
# talos: .taskfiles/talos
# volsync: .taskfiles/volsync
# workstation: .taskfiles/workstation
tasks:
  default:
    cmds:
      - task --list
    silent: true
  set_context:
    desc: "Set bws, kubernetes and talos context"
    preconditions:
      - test -f {{.CLUSTER_DIR }}/kubeconfig
    cmds:
      - echo "# Generated by set_context task" > {{.ROOT_DIR}}/k8s.env
      - echo "KUBECONFIG={{.CLUSTER_DIR }}/kubeconfig" >> {{.ROOT_DIR}}/k8s.env
      - echo "TALOSCONFIG={{.TALOS_CONFIG_DIR}}/talosconfig" >> {{.ROOT_DIR}}/k8s.env
      - echo "BWS_PROJECT={{.BWS_PROJECT}}" >> {{.ROOT_DIR}}/k8s.env
      - echo "BWS_ORG={{.BWS_ORG}}" >> {{.ROOT_DIR}}/k8s.env
      - echo "context set to {{.CLUSTER}}"
  unset_context:
    desc: "Remove kubernetes and talos context"
    cmds:
      - echo "# Generated by unset_context task" > {{.ROOT_DIR}}/k8s.env

# Ref: https://github.com/go-task/task/issues/608
# noop:
#   internal: true
#   silent: true
#   cmd: noop() { :; }
