# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
set: [pipefail]
shopt: [globstar]
vars:
  BOOSTRAP_DIR: '{{.ROOT_DIR}}/bootstrap'
  CLUSTER: '{{.CLUSTER | default "dev"}}'
  CLUSTER_APPS: '{{.ROOT_DIR}}/kubernetes/apps/{{.CLUSTER}}'
  CLUSTER_DIR: '{{.ROOT_DIR}}/kubernetes/clusters/{{.CLUSTER}}'
  SCRIPTS_DIR: '{{.ROOT_DIR}}/scripts'
  SHARED_APPS: '{{.ROOT_DIR}}/kubernetes/apps/base'
  TALOS_DIR: '{{.ROOT_DIR}}/talos/{{.CLUSTER}}'
  TALOS_CONFIG_DIR: '{{.ROOT_DIR}}/talos/{{.CLUSTER}}/clusterconfig'
  TERRAFORM_DIR: '{{.ROOT_DIR}}/terraform'
  ANSIBLE_DIR: '{{.ROOT_DIR}}/ansible'
dotenv:
  - '{{.ROOT_DIR}}/bws.env'
  # - '{{.SHARED_APPS}}/kube-tools/system-upgrade/versions.env'
env:
  # KUBECONFIG: '{{.CLUSTER_DIR}}/kubeconfig'
  # MINIJINJA_CONFIG_FILE: '{{.ROOT_DIR}}/.minijinja.toml'
  # SOPS_AGE_KEY_FILE: '{{.ROOT_DIR}}/age.key'
  TALOSCONFIG: '{{.TALOS_DIR}}/clusterconfig/talosconfig'
includes:
  bootstrap: taskfiles/bootstrap
  status: taskfiles/status
  terraform: taskfiles/terraform
  ansible: taskfiles/ansible
# kubernetes: .taskfiles/kubernetes
# op: .taskfiles/onepassword
# sops: .taskfiles/sops
# talos: .taskfiles/talos
# volsync: .taskfiles/volsync
# workstation: .taskfiles/workstation
tasks:
  default:
    cmd: task --list
    silent: true

# Ref: https://github.com/go-task/task/issues/608
# noop:
#   internal: true
#   silent: true
#   cmd: noop() { :; }
