- block:
  - name: create config folder
    ansible.builtin.file:
      path: /home/ipreston/homepage_config
      state: directory
      mode: '0700'
      owner: root
      group: docker

  - name: Copy over configs
    ansible.builtin.template:
      src: "{{ item }}.yaml.j2"
      dest: "/home/ipreston/homepage_config/{{ item }}.yaml"
      owner: root
      group: docker
      mode: '0600'
    with_items:
      - settings
      - services
      - widgets
      - bookmarks
      - docker
  become: true

- name: Create homepage container
  community.docker.docker_container:
    name: homepage
    hostname: homepage
    networks:
      - name: traefik_net
    image: "ghcr.io/gethomepage/homepage:v0.9.1"
    state: "started"
    container_default_behavior: compatibility
    comparisons:
      labels: strict
    restart_policy: unless-stopped
    env:
      TZ: "America/Edmonton"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/ipreston/homepage_config:/app/config
    labels:
      traefik.enable: "true"
      traefik.http.routers.homepage.entrypoints: https
      traefik.http.routers.homepage.rule: Host(`homepage.{{ subdomain }}.ipreston.net`)
      traefik.http.routers.homepage.tls: "true"
      traefik.http.routers.homepage.middlewares: "chain-no-auth@file"
      traefik.http.routers.homepage.service: homepage
      traefik.http.services.homepage.loadbalancer.server.port: "3000"


