---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spierscraper-config
data:
  config.yaml: |
    filters:
      chinos:
        fits:
          - "Contemporary"
        sizes:
          - "34"
          - "33"
      sport_coats:
        fits:
          - "Contemporary"
        sizes:
          - "34R"
      shirts:
        fits:
          - "Contemporary"
          - "L"
          - "M"
          - "15.5"
        sizes:
          - "34"
      outerwear:
        fits:
          - "Contemporary"
          - "L (42)"
          - "M (40)"
        sizes:
          - "40"
          - "42"
      knitwear:
        fits:
          - "M"
      other:
        fits:
            - 'Contemporary'
            - "L"
            - "L (42)"
            - "M"
            - "M (40)"
    rate_limit_seconds: 1.5
    cache_ttl_hours: 24
    cache_path: "/data/cache"
