---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spierscraper
components:
  - ../../../components/namespace
resources:
  - ./configmap.yaml
  - ./external-secret.yaml
  - ./cronjob.yaml
