# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: "not-used"
      sourceRef:
        kind: HelmRepository
        name: traefik
  values:
    service:
      enabled: true
      type: LoadBalancer
      labels:
        lb-pool: ip-pool
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true # <-- Change this to false if you want a temporary redirect
    ingressRoute:
      dashboard:
        enabled: true
        entryPoints:
          - websecure
        matchRule: Host(`traefik.${subdomain}.ipreston.net`)
        # middlewares:
        #   - name: traefik-web-ui-middleware  # <-- Replace with your authentication middleware
        tls:
          secretName: traefik-web-ui-tls
