apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/rancher/local-path-provisioner/deploy?ref=v0.0.32
patches:
  - patch: "kind: ConfigMap\napiVersion: v1\nmetadata:\n  name: local-path-config\n  namespace: local-path-storage\ndata:\n  config.json: |-\n    {\n            \"nodePathMap\":[\n            {\n                    \"node\":\"DEFAULT_PATH_FOR_NON_LISTED_NODES\",\n                    \"paths\":[\"/var/local-path-provisioner\"]\n            }\n            ]\n    }    "
  - patch: "apiVersion: storage.k8s.io/v1\nkind: StorageClass\nmetadata:\n  name: local-path\n  annotations:\n    storageclass.kubernetes.io/is-default-class: \"true\"    "
  - patch: "apiVersion: v1\nkind: Namespace\nmetadata:\n  name: local-path-storage\n  labels:\n    pod-security.kubernetes.io/enforce: privileged    "
