apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kube-prometheus-stack-grafana
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: admin-user
      remoteRef:
        key: "GRAFANA_USER"
    - secretKey: admin-password
      remoteRef:
        key: "GRAFANA_PASS"
