# yaml-language-server: $schema=https://json.schemastore.org/component
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
# Apply the same patches you had in base
patches:
  - patch: |-
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: local-path-config
        namespace: local-path-storage
      data:
        config.json: |-
          {
                  "nodePathMap":[
                  {
                          "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                          "paths":["/var/mnt/localpath"]
                  }
                  ]
          }
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: local-path-storage
        labels:
          pod-security.kubernetes.io/enforce: privileged
