---

- name: Install starship
  become: true
  ansible.builtin.package:
    name: starship
    state: present

- name: Configure starship for fish
  ansible.builtin.lineinfile:
    path: /home/ipreston/.config/fish/config.fish
    line: '    starship init fish | source'
    insertbefore: "end"

- name: Copy over starship config
  ansible.builtin.copy:
    src: starship.toml
    dest: /home/ipreston/.config/starship.toml