- name: Create komga app volume
  community.docker.docker_volume:
    name: mealie_vol
- name: Create comics network
  community.docker.docker_network:
    name: comics_network
- name: Create komga container
  community.docker.docker_container:
    name: komga
    hostname: komga
    networks:
      - name: comics_network
      - name: traefik_net
    image: gotson/komga:1.23.3
    image_name_mismatch: recreate
    state: "started"
    container_default_behavior: compatibility
    comparisons:
      labels: strict
    restart_policy: unless-stopped
    exposed_ports:
      - "9000"
    volumes:
      - "komga_vol:/config"
      - "comics_smb_vol:/data"
    env:
      TZ: "America/Edmonton"
    labels:
      traefik.enable: "true"
      traefik.http.routers.komga.entrypoints: https
      traefik.http.routers.komga.rule: Host(`komga.{{ subdomain }}.ipreston.net`)
      traefik.http.routers.komga.tls: "true"
      traefik.http.routers.komga.middlewares: "chain-no-auth@file"
      traefik.http.routers.komga.service: komga
      traefik.http.services.komga.loadbalancer.server.port: "25600"
