# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spegel
spec:
  interval: 30m
  chart:
    spec:
      chart: spegel
      version: "v0.4.0"
      sourceRef:
        kind: HelmRepository
        name: spegel
