---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-backup-creds
  namespace: ${APP}
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: cnpg-backup-creds
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: CNPG_BUCKET_KEY_ID
    - secretKey: SECRET_ACCESS_KEY
      remoteRef:
        key: CNPG_BUCKET_KEY_SECRET
