---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: ${APP}-cnpg-db-daily
  namespace: ${APP}
spec:
  schedule: "0 2 * * 6"
  backupOwnerReference: self
  cluster:
    name: ${APP}-cnpg-db
