---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpaca
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alpaca
  template:
    metadata:
      labels:
        app: alpaca
    spec:
      containers:
        - name: kuard
          image: gcr.io/kuar-demo/kuard-amd64:green
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: alpaca
spec:
  selector:
    app: alpaca
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

