apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cnpg-system
    server: https://kubernetes.default.svc
  project: cluster
  sources:
    - repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: 0.23.2
      chart: cloudnative-pg
  syncPolicy:
    automated:
      # Turn these to true once the app is working
      prune: true
      selfHeal: true
    # CRD spec is too large to do this otherwise
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
