traefik:
  ports:
    web:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true  # <-- Change this to false if you want a temporary redirect

  ingressRoute:
    dashboard:
      enabled: true
      entryPoints:
        - websecure
      matchRule: Host(`traefik.dk8s.ipreston.net`)  # <-- Replace with a secret for the base domain eventually
      # middlewares:
      #   - name: traefik-web-ui-middleware  # <-- Replace with your authentication middleware
      tls:
        secretName: traefik-web-ui-tls  # <-- Replace with your TLS secret name
