apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-cert
  namespace: homepage
spec:
  secretName: homepage-web-ui-tls
  dnsNames:
    - homepage.<path:subdomain#SUBDOMAIN>
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage-ingress
  namespace: homepage
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`homepage.<path:subdomain#SUBDOMAIN>`) # <-- Replace with your FQDN
      kind: Rule
      services:
        - name: homepage
          kind: Service
          port: 3000
  tls:
    secretName: homepage-web-ui-tls
