openebs:
  base:
    metrics:
      enabled: false
  localpv-provisioner:
    localpv:
      basePath: "/var/local/openebs/local"
  mayastor:
    etcd:
      localpvScConfig:
        basePath: "/var/local/openebs"
    loki-stack:
      localpvScConfig:
        basePath: "/var/local/openebs"
    io_engine:
      envcontext: "iova-mode=pa"
    csi:
      node:
        initContainers:
          enabled: false
  engines:
    local:
      lvm:
        enabled: false
      zfs:
        enabled: false
