apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-web-ui-cert
  namespace: longhorn-system
spec:
  secretName: longhorn-web-ui-tls
  dnsNames:
    - longhorn.<path:subdomain#SUBDOMAIN>
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`longhorn.<path:subdomain#SUBDOMAIN>`) # <-- Replace with your FQDN
      priority: 10
      kind: Rule
      services:
        - name: longhorn-frontend
          port: 80
  tls:
    secretName: longhorn-web-ui-tls
