apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: reloader
    server: https://kubernetes.default.svc
  project: cluster
  source:
    path: k8s/dev/services/reloader/chart
    repoURL: https://github.com/ianepreston/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      # Turn these to true once the app is working
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
