---

- name: Create organizr app volume
  community.docker.docker_volume:
    name: organizr_vol

- name: Create organizr container
  community.docker.docker_container:
    name: organizr
    hostname: organizr
    networks:
      - name: traefik_net
    image: organizr/organizr:latest
    state: "{{ organizr_container_state }}"
    container_default_behavior: compatibility
    restart_policy: unless-stopped
    exposed_ports:
      - "80"
    volumes:
      - "organizr_vol:/config"
    env:
      TZ: "America/Edmonton"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "true"
      traefik.http.routers.organizr.rule: Host(`organizr.{{ subdomain }}.ipreston.net`)
      traefik.http.routers.organizr.service: organizr
      traefik.http.services.organizr.loadbalancer.server.port: "80"
      traefik.http.routers.organizr.entrypoints: web
