apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kuard-web-ui-cert
  namespace: kuard
spec:
  dnsNames:
    - dev-kuard.dk8s.ipreston.net
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kuard-ingress
  namespace: kuard
spec:
  routes:
    - match: Host(`dev-kuard.dk8s.ipreston.net`) # <-- Replace with your FQDN
