---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-web-ui-cert
  namespace: traefik
spec:
  secretName: traefik-web-ui-tls
  dnsNames:
    - traefik.<path:subdomain#SUBDOMAIN>
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
