---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: certmanager-cloudflare-token
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    # This name must match the metadata.name in the `SecretStore`
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: CERT_MANAGER_CLOUDFLARE_TOKEN
    remoteRef:
      key: "CERT_MANAGER_CLOUDFLARE_TOKEN"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: certmanager-cloudflare-token
              key: CERT_MANAGER_CLOUDFLARE_TOKEN
        selector: {}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: certmanager-cloudflare-token
              key: CERT_MANAGER_CLOUDFLARE_TOKEN
        selector: {}
