# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ./spegel.yaml
patches:
  - path: ./patch-ocirepository.yaml
    target:
      group: source.toolkit.fluxcd.io
      version: v1
      kind: OCIRepository
      name: spegel
