- name: Create calibre volume
  community.docker.docker_volume:
    name: calibre_vol

- name: Create books network
  community.docker.docker_network:
    name: books_network

- name: Start calibre
  community.docker.docker_container:
    name: calibre
    hostname: calibre
    image: linuxserver/calibre-web:0.6.23
    image_name_mismatch: recreate
    networks:
      - name: "books_network"
      - name: traefik_net
    state: started
    container_default_behavior: "compatibility"
    comparisons:
      labels: strict
    env:
      TZ: "America/Edmonton"
      PUID: "1026"
      PGID: "100"
      DOCKER_MODS: "linuxserver/mods:universal-calibre"
    restart_policy: unless-stopped
    volumes:
      - "calibre_vol:/config"
      - "books_vol:/books"
    exposed_ports:
      - "8083"
    labels:
      traefik.enable: "true"
      traefik.http.routers.calibre.entrypoints: https
      traefik.http.routers.calibre.rule: Host(`calibre.{{ subdomain }}.ipreston.net`)
      traefik.http.routers.calibre.tls: "true"
      traefik.http.routers.calibre.middlewares: "chain-no-auth@file"
      traefik.http.routers.calibre.service: calibre
      traefik.http.services.calibre.loadbalancer.server.port: "8083"


