# yaml-language-server: $schema=https://kube-schemas.pages.dev/cilium.io/ciliumbgppeeringpolicy_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: bgp-peering-policy-pfsense
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: "linux" # just match everything
  virtualRouters:
    - localASN: 0000 # Overriden in patch
      serviceSelector:
        matchExpressions:
          - {key: "io.cilium/bgp-announce", operator: NotIn, values: ['fakevalue']} # Should match all
      neighbors:
        - peerAddress: '192.168.40.1/32'
          peerASN: 64512
          eBGPMultihopTTL: 10
          connectRetryTimeSeconds: 120
          holdTimeSeconds: 90
          keepAliveTimeSeconds: 30
          gracefulRestart:
            enabled: true
            restartTimeSeconds: 120
