# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ../base
  - ./bgp-peering.yaml
  - ./l2-announcement.yaml
  - ./loadbalancer-ippool.yaml
