# yaml-language-server: $schema=https://kube-schemas.pages.dev/cilium.io/cliluml2announcementpolicy_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: infra-l2
spec:
  serviceSelector:
    matchLabels:
      lb-pool: ip-pool
  interfaces:
    - "^eth0$"
  loadBalancerIPs: true
