---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bandicoot-prod
  labels:
    app: bandicoot
    env: prod
    ver: "1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bandicoot
      env: prod
  template:
    metadata:
      labels:
        app: bandicoot
        env: prod
        ver: "1"
    spec:
      containers:
        - name: bandicoot-prod
          image: gcr.io/kuar-demo/kuard-amd64:blue
