# yaml-language-server: $schema=https://kube-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kuard-web-ui-cert
  namespace: kuard
spec:
  secretName: kuard-web-ui-tls
  dnsNames:
    - kuard.dk8s.ipreston.net
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kuard-ingress
  namespace: kuard
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`kuard.dk8s.ipreston.net`)
      kind: Rule
      services:
        - name: kuard
          port: 80
  tls:
    secretName: kuard-web-ui-tls
