---

- name: Create hoarder meili volume
  community.docker.docker_volume:
    name: hoarder_meili_vol

- name: Create hoarder volume
  community.docker.docker_volume:
    name: hoarder_vol

- name: Create hoarder network
  community.docker.docker_network:
    name: hoarder_net

- name: Create meilisearch container for hoarder
  community.docker.docker_container:
    name: hoarder-meilisearch
    hostname: hoarder-meilisearch
    networks:
      - name: hoarder_net
    image: getmeili/meilisearch:v1.14.0
    image_name_mismatch: recreate
    state: "started"
    container_default_behavior: compatibility
    env:
      TZ: "America/Edmonton"
      MEILI_NO_ANALYTICS: "true"
      MEILI_MASTER_KEY: "{{ hoarder_meili_key }}"
      NEXTAUTH_URL: "https://hoarder.{{ subdomain }}.ipreston.net"
      NEXTAUTH_SECRET: "{{ hoarder_nextauth_key }}"
    restart_policy: unless-stopped
    volumes:
      - "hoarder_meili_vol:/meili_data"

- name: Create chrome container for hoarder
  community.docker.docker_container:
    name: hoarder-chrome
    hostname: hoarder-chrome
    networks:
      - name: hoarder_net
    image: gcr.io/zenika-hub/alpine-chrome:124
    image_name_mismatch: recreate
    state: "started"
    container_default_behavior: compatibility
    env:
      TZ: "America/Edmonton"
      NEXTAUTH_URL: "https://hoarder.{{ subdomain }}.ipreston.net"
      NEXTAUTH_SECRET: "{{ hoarder_nextauth_key }}"
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    restart_policy: unless-stopped

- name: Create hoarder container
  community.docker.docker_container:
    name: hoarder
    hostname: hoarder
    networks:
      - name: hoarder_net
      - name: traefik_net
    image: "ghcr.io/hoarder-app/hoarder:0.19.0"
    image_name_mismatch: recreate
    state: "started"
    container_default_behavior: compatibility
    comparisons:
      labels: strict
    restart_policy: unless-stopped
    volumes:
      - "hoarder_vol:/data"
    exposed_ports:
      - "3000"
    env:
      TZ: "America/Edmonton"
      MEILI_ADDR: http://hoarder-meilisearch:7700
      MEILI_MASTER_KEY: "{{ hoarder_meili_key }}"
      NEXTAUTH_URL: "https://hoarder.{{ subdomain }}.ipreston.net"
      NEXTAUTH_SECRET: "{{ hoarder_nextauth_key }}"
      BROWSER_WEB_URL: http://hoarder-chrome:9222
      OPENAI_API_KEY: "{{ hoarder_openai_key}}"
      DATA_DIR: "/data"
    labels:
      traefik.enable: "true"
      traefik.http.routers.hoarder.entrypoints: https
      traefik.http.routers.hoarder.rule: Host(`hoarder.{{ subdomain }}.ipreston.net`)
      traefik.http.routers.hoarder.tls: "true"
      traefik.http.routers.hoarder.middlewares: "chain-no-auth@file"
      traefik.http.routers.hoarder.service: hoarder
      traefik.http.services.hoarder.loadbalancer.server.port: "3000"
      traefik.frontend.redirect.permanent: "true"

