---

- name: Install neovim
  become: true
  ansible.builtin.package:
    name: neovim
    state: present

- name: Alias nvim as vim
  ansible.builtin.copy:
    src: nvim.fish
    dest: /home/ipreston/.config/fish/conf.d/nvim.fish

- name: Copy nvim config
  ansible.builtin.copy:
    src: nvim
    dest: /home/ipreston/.config/nvim

