---
- name: Set up prod docker host
  hosts: ares
  vars_files:
    - variables/secrets.yml
  roles:
    - dockerserver/docker
    # - dockerserver/watchtower
    - dockerserver/unifi
    - dockerserver/mediavols
    - dockerserver/traefik
    - dockerserver/homepage
    - dockerserver/actualbudget
    - dockerserver/arr
    # - dockerserver/calibre
    - dockerserver/jellyfin
    - dockerserver/jellyseerr
    - dockerserver/tubesync
    - dockerserver/komga
    - dockerserver/mealie
    - dockerserver/miniflux
    - dockerserver/memos
    - dockerserver/wallabag
    - dockerserver/hoarder
