---
# Playbook for my dev mars box

- name: Example from an Ansible Playbook
  hosts: dmars
  vars_files:
    - variables/secrets.yml
  roles:
    - dockerserver/docker
    - dockerserver/traefik
    - dockerserver/miniflux
    - dockerserver/mealie