---
# Playbook for my dev mars box

- name: Example from an Ansible Playbook
  hosts: dmars
  vars_files:
    - variables/secrets.yml
  roles:
    - docker
    - traefik
    - miniflux
    - mealie
    - organizr