---
# Playbook for my dev mars box

- name: Example from an Ansible Playbook
  hosts: dmars
  vars:
    organizr_container_state: "absent"
  vars_files:
    - variables/secrets.yml
  roles:
    - docker
    - watchtower
    - traefik
    - mealie
    - organizr