---
- name: Set up dev mars for testing
  hosts: dmars
  vars_files:
    - variables/secrets.yml
  roles:
    - dockerserver/docker
    - dockerserver/traefik
    - dockerserver/miniflux
    - dockerserver/mealie