---
- name: Set up dev mars for testing
  hosts: dmars
  vars_files:
    - variables/secrets.yml
  roles:
    # - dockerserver/docker
    # - dockerserver/watchtower
    # - dockerserver/unifi
    # - dockerserver/mediavols
    # - dockerserver/traefik
    # - dockerserver/homepage
    # - dockerserver/arr
    # - dockerserver/calibre-desktop
    # - dockerserver/calibre
    # - dockerserver/jellyfin
    # - dockerserver/jellyseerr
    # - dockerserver/komga
    # - dockerserver/mealie
    # - dockerserver/miniflux
    # - dockerserver/ytdl