---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPConfig
metadata:
  name: bgp-config
spec:
  localASN: 64500
  peers:
    - peerAddress: 192.168.40.1
      peerASN: 64501
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: bgp-policy
spec:
  peers:
    - name: pfsense
      config:
        peerAddress: 192.168.40.1
        peerASN: 64501
  selectors:
    - matchLabels:
        pool: lab-pool
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: lab-pool
spec:
  addresses:
    - start: "192.168.40.21"
      stop: "192.168.40.30"
  avoidBuggyIPs: true
