apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi # Size is arbitrary for NFS, adjust as needed
  accessModes:
    - ReadWriteMany # RWX for multiple pods
  persistentVolumeReclaimPolicy: Retain # Keeps data after PVC deletion
  storageClassName: nfs # Optional, define if using dynamic provisioning later
  mountOptions:
    - hard
    - nfsvers=4.1 # Adjust NFS version as needed
  nfs:
    server: 192.168.10.3 # Your NFS server IP or hostname
    path: /volume1/storagetesting # Specific folder in the NFS share
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dbench-pv-claim
spec:
  storageClassName: nfs
  volumeName: nfs-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dbench
spec:
  template:
    spec:
      containers:
        - name: dbench
          image: zayashv/dbench:latest
          imagePullPolicy: Always
          env:
            - name: DBENCH_MOUNTPOINT
              value: /data
              # - name: DBENCH_QUICK
              #   value: "yes"
              # - name: FIO_SIZE
              #   value: 1G
              # - name: FIO_OFFSET_INCREMENT
              #   value: 256M
              # - name: FIO_DIRECT
              #   value: "0"
          volumeMounts:
            - name: dbench-pv
              mountPath: /data
      restartPolicy: Never
      volumes:
        - name: dbench-pv
          persistentVolumeClaim:
            claimName: dbench-pv-claim
  backoffLimit: 4
