---
apiVersion: v1
kind: Namespace
metadata:
  name: kuard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
  namespace: kuard
  labels:
    run: kuard
spec:
  selector:
    matchLabels:
      run: kuard
  replicas: 1
  template:
    metadata:
      labels:
        run: kuard
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:blue
        env:
            - name: TEST_INLINE_SECRET
              value: "<path:bitwarden-kuard-test#test"
            - name: TEST_SECRET
              valueFrom:
                secretKeyRef:
                  name: bitwarden-kuard-test
                  key: test
