# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: "not-used"
      sourceRef:
        kind: HelmRepository
        name: cilium
  values:
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
      tls:
        enabled: true
        auto:
          enabled: true
          method: helm
    ipam:
      mode: kubernetes
    kubeProxyReplacement: true
    securityContext:
      capabilities:
        ciliumAgent:
          - "CHOWN"
          - "KILL"
          - "NET_ADMIN"
          - "NET_RAW"
          - "IPC_LOCK"
          - "SYS_ADMIN"
          - "SYS_RESOURCE"
          - "DAC_OVERRIDE"
          - "FOWNER"
          - "SETGID"
          - "SETUID"
        cleanCiliumState:
          - "NET_ADMIN"
          - "SYS_ADMIN"
          - "SYS_RESOURCE"
    cgroup:
      autoMount:
        enabled: false
      hostRoot: "/sys/fs/cgroup/"
    k8sServiceHost: "not-used"
    k8sServicePort: 6443
    l2announcements:
      enabled: true
    devices: "eth0,eth0.15,eth0.30"
    bgpControlPlane:
      enabled: true
